### ISSUE TITLE
Social strategy for Beat 4

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#142] opened 2016-02-18 01:30 UTC

**Comment by HPaulJohnson** [comment] 2016-03-04 20:59
We've been working on ideas in ticket #143 

Plan for next phase of social is now being tracked in this doc: 
https://docs.google.com/document/d/1TQwKVN_A-KwCNVevD_IBIUET4q_r87qxm0SZfHdLV5c/edit

Working on a set of 5 ideas for this phase to be used across FB, Tiwtter and paid.

**Comment by HPaulJohnson** [comment] 2016-03-04 21:02
Duplicate of #144

**Closed as completed by HPaulJohnson** 2016-03-04 21:02 UTC
