### ISSUE TITLE
Update beat 2 landing page

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#147] opened 2016-02-18 01:32 UTC

**Comment by OpenMatt** [comment] 2016-02-19 18:09
@alanmoo any status update on this one?

**Comment by alanmoo** [comment] 2016-02-19 18:10
AFAIK this is effectively the same as adding the playlist, just making the site land on the Beat 2 video/details. Is that correct, @lovegushwa?

**Comment by brettgaylor** [comment] 2016-02-23 17:45
@alanmoo here's two tickets
https://github.com/MozillaFoundation/encryption_campaign/issues/171
https://github.com/MozillaFoundation/encryption_campaign/issues/172

**Comment by alanmoo** [comment] 2016-02-23 17:48
Dupe of #146.

**Closed as completed by alanmoo** 2016-02-23 17:48 UTC
Labels: P1, Beat 2
